apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.4.3
    helm:
      releaseName: monitoring
      values: |
        grafana:
          adminPassword: admin

        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi

        alertmanager:
          config:
            route:
              receiver: "demo-webhook"
            receivers:
              - name: "demo-webhook"
                webhook_configs:
                  - url: "http://demo-app.demo.svc.cluster.local/"
                  - send_resolved: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
